apiVersion: builtin
kind: ReplacementTransformer
metadata:
  name: route-binding
replacements:
  - source:
      kind: ConfigMap
      name: prod-route-values
      fieldPath: data.GATEWAY_NAME
    targets:
      - select:
          group: gateway.networking.k8s.io
          version: v1
          kind: HTTPRoute
          labelSelector: route-binding.online-boutique.io/gateway=public-web
        fieldPaths:
          - spec.parentRefs.0.name

  - source:
      kind: ConfigMap
      name: prod-route-values
      fieldPath: data.GATEWAY_NAMESPACE
    targets:
      - select:
          group: gateway.networking.k8s.io
          version: v1
          kind: HTTPRoute
          labelSelector: route-binding.online-boutique.io/gateway=public-web
        fieldPaths:
          - spec.parentRefs.0.namespace

  - source:
      kind: ConfigMap
      name: prod-route-values
      fieldPath: data.HTTP_SECTION_NAME
    targets:
      - select:
          group: gateway.networking.k8s.io
          version: v1
          kind: HTTPRoute
          labelSelector: route-binding.online-boutique.io/gateway=public-web
        fieldPaths:
          - spec.hostnames.0

  - source:
      kind: ConfigMap
      name: prod-route-values
      fieldPath: data.HTTPS_SECTION_NAME
    targets:
      - select:
          group: gateway.networking.k8s.io
          version: v1
          kind: HTTPRoute
          labelSelector: route-binding.online-boutique.io/listener=http
        fieldPaths:
          - spec.parentRefs.0.sectionName

  - source:
      kind: ConfigMap
      name: prod-route-values
      fieldPath: data.HOSTNAME
    targets:
      - select:
          group: gateway.networking.k8s.io
          version: v1
          kind: HTTPRoute
          labelSelector: route-binding.online-boutique.io/listener=https
        fieldPaths:
          - spec.parentRefs.0.sectionName