apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: online-boutique-dev

resources:
  - ../../base
  - namespace.yaml

components:
  - ../../components/exposure/public-loadbalancer

labels:
  - pairs:
      app.kubernetes.io/part-of: online-boutique
      app.kubernetes.io/managed-by: kustomize
      environment: dev