apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: online-boutique-prod

resources:
  - ../../base
  - namespace.yaml
  - pdb.yaml
  - autoscaling
patches:
  - path: patches/http-route-prod.yaml
    target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: frontend-http-redirect

  - path: patches/https-route-prod.yaml
    target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: frontend

labels:
  - pairs:
      app.kubernetes.io/part-of: online-boutique
      app.kubernetes.io/managed-by: kustomize
      environment: prod
    includeTemplates: true