apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: online-boutique-prod

resources:
  - ../../base
  - namespace.yaml
  - pdb.yaml
  - autoscaling

components:
  - route-binding

labels:
  - pairs:
      app.kubernetes.io/part-of: online-boutique
      app.kubernetes.io/managed-by: kustomize
      environment: prod
    includeTemplates: true