apiVersion: v1
kind: ConfigMap
metadata:
  name: edgeapi-backend-config
  labels:
    app: edgeapi
    app.kubernetes.io/name: edgeapi
    app.kubernetes.io/component: edge-api
    app.kubernetes.io/part-of: online-boutique
data:
  BACKEND_PRODUCT_CATALOG_ADDR: "http://productcatalogservice:3550"
  BACKEND_CURRENCY_ADDR: "http://currencyservice:7000"
  BACKEND_CART_ADDR: "http://cartservice:7070"
  BACKEND_RECOMMENDATION_ADDR: "http://recommendationservice:8080"
  BACKEND_CHECKOUT_ADDR: "http://checkoutservice:5050"
  BACKEND_SHIPPING_ADDR: "http://shippingservice:50051"
  BACKEND_AD_ADDR: "http://adservice:9555"
  BACKEND_DEFAULT_CURRENCY: "ISK"