apiVersion: v1
kind: ConfigMap
metadata:
  name: edgeapi-backend-config
  labels:
    app: edgeapi
    app.kubernetes.io/name: edgeapi
    app.kubernetes.io/component: edge-api
    app.kubernetes.io/part-of: online-boutique
data:
  product_catalog_addr: "http://productcatalogservice:3550"
  currency_addr: "http://currencyservice:7000"
  cart_addr: "http://cartservice:7070"
  recommendation_addr: "http://recommendationservice:8080"
  checkout_addr: "http://checkoutservice:5050"
  shipping_addr: "http://shippingservice:50051"
  ad_addr: "http://adservice:9555"
  default_currency: "ISK"