apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgeapi
  labels:
    app: edgeapi
    app.kubernetes.io/name: edgeapi
    app.kubernetes.io/component: edge-api
    app.kubernetes.io/part-of: online-boutique
spec:
  selector:
    matchLabels:
      app: edgeapi
  template:
    metadata:
      labels:
        app: edgeapi
        app.kubernetes.io/name: edgeapi
        app.kubernetes.io/component: edge-api
        app.kubernetes.io/part-of: online-boutique
    spec:
      serviceAccountName: edgeapi
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: server
          image: ghcr.io/quasarray/edgeapi:dev
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          envFrom:
            - configMapRef:
                name: edgeapi-backend-config
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          startupProbe:
            httpGet:
              path: /livez
              port: http
            periodSeconds: 2
            failureThreshold: 30
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi