apiVersion: v1
kind: ServiceAccount
metadata:
  name: edgeapi
  labels:
    app: edgeapi
    app.kubernetes.io/name: edgeapi
    app.kubernetes.io/component: edge-api
    app.kubernetes.io/part-of: online-boutique
automountServiceAccountToken: false