# src/edge-api-rs/config/app-prod.toml
[backend]
product_catalog_addr = "${PRODUCT_CATALOG_SERVICE_ADDR:http://productcatalogservice:3550}"
currency_addr = "${CURRENCY_SERVICE_ADDR:http://currencyservice:7000}"
cart_addr = "${CART_SERVICE_ADDR:http://cartservice:7070}"
recommendation_addr = "${RECOMMENDATION_SERVICE_ADDR:http://recommendationservice:8080}"
checkout_addr = "${CHECKOUT_SERVICE_ADDR:http://checkoutservice:5050}"
shipping_addr = "${SHIPPING_SERVICE_ADDR:http://shippingservice:50051}"
ad_addr = "${AD_SERVICE_ADDR:http://adservice:9555}"
default_currency = "${DEFAULT_CURRENCY:ISK}"